name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: psf/black@stable
        with:
          args: ". --check"
      - uses: jamescurtin/isort-action@master
        with:
          configuration: "-check-only --diff --profile black"
          requirementsFiles: "requirements.txt"
